version: '3.8'

services:
  app:
    build: .
    container_name: tn_automation_runtime
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"